services:
  postgres:
    image: postgres:15
    container_name: b2borders-postgres
    environment:
      POSTGRES_DB: b2bOrders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - b2b-network

  redis:
    image: redis:7
    container_name: b2borders-redis
    ports:
      - "6379:6379"
    networks:
      - b2b-network

volumes:
  postgres-data:

networks:
  b2b-network:
    driver: bridge